export const EXIT = {
  OK: 0,
  GENERIC_FAILURE: 1,
  USAGE: 2,
  AUTH_FAILURE: 10,
  KEYCHAIN_UNAVAILABLE: 11,
  NO_SESSIONS_FOUND: 20,
  ANONYMIZATION_FAILURE: 30,
  NETWORK_FAILURE: 40,
  ENDPOINT_UNREACHABLE: 41,
  VERSION_GATE_FAILURE: 50,
  INSPECT_DIR_EXISTS: 60,
} as const;

export type ExitCode = (typeof EXIT)[keyof typeof EXIT];
